codecov:
  require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

fixes:
  - "/home/runner/work/system-76-keyboards/system-76-keyboards/::"
